api_platform:
  title: Padlok API
  version: '%env(string:API_VERSION)%'
  show_webby: false
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/src/ApiPlatform/Dto'
  formats:
    json:
      - 'application/json'
    html:
      - 'text/html'
  name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
  enable_docs: false
  enable_swagger: false
  enable_swagger_ui: false
  defaults:
    input_formats: ['json']
    output_formats: ['json']
