api_platform:
  title: Padlok API
  version: '%env(string:API_VERSION)%'
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/src/ApiPlatform/Dto'
  formats:
    json: ['application/json']
  docs_formats:
    jsonopenapi: [ 'application/vnd.openapi+json' ]
    html: ['text/html']
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

  enable_docs: '%env(bool:APP_DEBUG)%'
  enable_swagger: '%env(bool:SWAGGER_ENABLED)%'
  enable_swagger_ui: '%env(bool:SWAGGER_ENABLED)%'
  name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
  show_webby: false
