name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test -v
      - name: Build debug
        run: swift build -v
      - name: Build release
        run: swift build -c release -v
      - name: Archive builds
        run: cd .build && tar -czf ../build.tar.gz x86_64-unknown-linux-gnu debug.yaml debug release.yaml release
        run: tar -czvf build.tar.gz .build/
      - name: Upload builds archive
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar.gz
