name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test -v
      - name: Build debug
        run: swift build -v
      - name: Build release
        run: swift build -c release -v
      - name: Archive builds
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: .build