name: Deploy in dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Build the stack
        run: docker-compose up -d

      - name: Tests
        run: composer test

      - name: Remove dev dependencies
        run: APP_ENV=prod APP_DEBUG=0 composer install --no-dev --optimize-autoloader --prefer-dist --no-progress --no-suggest

      - name: Warm cache
        run: rm -rf var/cache/* && APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear

      - name: Rsync deploy
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --chown=${{ secrets.DEPLOY_USER }}:www-data --exclude '.env.local' --exclude '.env.*.local'
          path: /
          remote_path: ${{ secrets.DEPLOY_PATH_DEV }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
